# Generated by Django 4.2.7 on 2023-12-01 07:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_categories__id_alter_customadmin__id_and_more'),
        ('user', '0002_alter_customuser__id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('total', models.FloatField()),
                ('payable_amount', models.FloatField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usercart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.products')),
            ],
        ),
    ]
