# Generated by Django 5.0 on 2023-12-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser__id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_profile_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
    ]
