# Generated by Django 5.0 on 2023-12-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usercart_cartproducts'),
        ('user', '0006_customuser_user_profile_image_thumbnail'),
    ]

    operations = [
    ]
