# Generated by Django 5.0 on 2023-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_merge_20231211_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
