# Generated by Django 5.0 on 2023-12-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_user_profile_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_image_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
