# Generated by Django 5.0 on 2023-12-11 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_admin', '0003_alter_categories__id_alter_customadmin__id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyProduct',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.customadmin')),
            ],
        ),
    ]
