# Generated by Django 5.0 on 2023-12-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0011_fcmdevice_fcm_django_registration_id_user_id_idx'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFCMDevice',
            fields=[
                ('fcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fcm_django.fcmdevice')),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=('fcm_django.fcmdevice',),
        ),
    ]
